export const lessons=[
{title:'Özünü tanı və hədəf seç',text:'İlk addım: maraqlarını, bacarıqlarını və sınamaq istədiyin sahələri ayrı siyahılara yaz. Hər sahə üçün kiçik bir sınaq seç: tələbə klubunda layihə, könüllülük və ya tanışlıq görüşü. Hədəfi konkret qur: növbəti 14 gündə bir layihəni bitirmək. Nəticəni gördükdən sonra istiqamətini yenilə.',question:'Başlanğıc üçün hansı hədəf daha ölçülə biləndir?',options:['Uğurlu olmaq','14 gündə bir portfolio layihəsi bitirmək','Hər şeyi öyrənmək'],answer:1},
{title:'Nəticə göstərən CV',text:'CV-də əlaqə məlumatlarını, qısa profilini, təhsilini, təcrübə və layihələrini göstər. Şəxsiyyət vəsiqəsi, ailə vəziyyəti və ev ünvanı lazım deyil. Hər fəaliyyət üçün nə etdiyini və nəticəni yaz: “5 nəfərlik komandada tələbə tədbirinin qeydiyyatını idarə etdim”. Təcrübən azdırsa, dərs layihələrini, könüllülüyü və kurs layihələrini əlavə et. Göndərməzdən əvvəl əlaqə məlumatlarını və yazı səhvlərini yoxla.',question:'CV-də hansı cümlə daha faydalıdır?',options:['Çox çalışqanam','Tədbirdə 80 iştirakçının qeydiyyatını təşkil etdim','Mən hər işi bacarıram'],answer:1},
{title:'Müsahibədə STAR üsulu',text:'Davranış suallarına real nümunə ilə cavab ver. Situasiya: vəziyyət nə idi? Tapşırıq: sənin məsuliyyətin nə idi? Addım: konkret nə etdin? Nəticə: nə dəyişdi və nə öyrəndin? Komandanın işini öz adına çıxma. İş təcrübən yoxdursa, universitet və könüllülük təcrübəsini istifadə et. Sonda rolun gündəlik işi və inkişaf imkanları haqqında sual ver.',question:'STAR cavabında hansı hissə vacibdir?',options:['Yalnız şirkət haqqında məlumat','Konkret addım və nəticə','Əzbərlənmiş ümumi cümlələr'],answer:1}
];
const orgs=[['socar','SOCAR','Enerji','company'],['bp','bp','Enerji','company'],['mcdonalds','McDonald’s','Restoran','company'],['kfc','KFC','Restoran','company'],['burger-king','Burger King','Restoran','company'],['pull-bear','Pull&Bear','Pərakəndə','company'],['new-yorker','New Yorker','Pərakəndə','company'],['adnsu','ADNSU','Universitet','university'],['unec','UNEC','Universitet','university'],['bdu','BDU','Universitet','university'],['ada','ADA Universiteti','Universitet','university']];
export async function seed(db){
 if(await db.prepare("SELECT value FROM settings WHERE key='seed-v1'").first())return;
 const now=Date.now();const items=orgs.map(([id,title,sector,type])=>({id,kind:'organization',title,body:{sector,type,city:'Bakı',description:'Kataloq profili. Təşkilatın nümayəndəsi tərəfindən hələ təsdiqlənməyib. Burada göstərilməsi tərəfdaşlıq demək deyil.',unclaimed:true}}));
 items.push({id:'bura-studio',kind:'organization',title:'BURA Sınaq Studiyası',body:{sector:'İcma',type:'club',city:'Onlayn',sample:true,description:'Platformanın müraciət və tədbir axınlarını yoxlamaq üçün nümunə təşkilat.'}},
 {id:'first-steps',kind:'course',title:'İlk addım: özünü tanı, CV hazırla',body:{category:'Karyera bacarıqları',duration:'25 dəqiqə',level:'Başlanğıc',description:'Üç qısa dərs, üç yoxlama sualı və şəxsi fəaliyyət planı.',lessons:lessons.map(({answer,...x})=>x)},private:{answers:lessons.map(x=>x.answer)}},
 {id:'practice-intern',kind:'opportunity',title:'İcma layihəsi koordinatoru',org:'bura-studio',body:{category:'Təcrübə',city:'Bakı',format:'Hibrid',sample:true,description:'Nümunə elan: tələbə tədbirinin planını hazırlamaq, komanda ilə tapşırıqları bölüşmək və nəticələri təqdim etmək. Müraciət axınını burada yoxlaya bilərsən. Bu, real iş təklifi deyil.',requirements:'Tələbə və ya yeni məzun; Azərbaycan dilində ünsiyyət; həftədə 5 saat.',deadline:'2027-12-31'}},
 {id:'practice-volunteer',kind:'opportunity',title:'Birlikdə öyrənək — könüllü mentor',org:'bura-studio',body:{category:'Könüllülük',city:'Onlayn',format:'Uzaqdan',sample:true,description:'Nümunə proqram: yeni tələbələrə öyrənmə planı hazırlamaqda dəstək. Platformanın könüllülük müraciətini yoxlamaq üçündür.',requirements:'Öyrəndiklərini paylaşmaq həvəsi.',deadline:'2027-12-31'}},
 {id:'practice-freelance',kind:'opportunity',title:'Tələbə klubu üçün sosial media dizaynı',org:'bura-studio',body:{category:'Freelance',city:'Onlayn',format:'Uzaqdan',sample:true,description:'Nümunə layihə: üç sosial media paylaşımı üçün dizayn konsepti. Test müraciətidir, ödənişli müqavilə deyil.',requirements:'Portfolio və ya bir nümunə iş.',deadline:'2027-12-31'}},
 {id:'practice-event',kind:'event',title:'Gələcəyini birlikdə planla',org:'bura-studio',body:{category:'Workshop',city:'Onlayn',sample:true,date:'2027-02-20T14:00:00+04:00',capacity:50,description:'Sınaq tədbiri. Qeydiyyat, bilet və ləğvetmə axınını yoxla. Real görüş keçirilməyəcək.'}});
 const stmts=items.map(i=>db.prepare('INSERT OR IGNORE INTO content (id,kind,title,organization_id,status,body,private_data,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(i.id,i.kind,i.title,i.org||null,'published',JSON.stringify(i.body),JSON.stringify(i.private||{}),now,now));
 stmts.push(db.prepare("INSERT OR IGNORE INTO settings (key,value) VALUES ('seed-v1','1')"));await db.batch(stmts);
}
