import {sqliteTable,text,integer,uniqueIndex,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{
 id:text('id').primaryKey(),handle:text('handle').notNull(),name:text('name').notNull(),email:text('email').notNull(),passwordHash:text('password_hash'),recoveryHash:text('recovery_hash'),role:text('role').notNull().default('member'),profile:text('profile').notNull().default('{}'),createdAt:integer('created_at').notNull(),disabled:integer('disabled').notNull().default(0)
},t=>[uniqueIndex('users_handle').on(t.handle),uniqueIndex('users_email').on(t.email)]);
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),csrf:text('csrf').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('sessions_user').on(t.userId)]);
export const content=sqliteTable('content',{id:text('id').primaryKey(),kind:text('kind').notNull(),title:text('title').notNull(),organizationId:text('organization_id'),ownerId:text('owner_id').references(()=>users.id,{onDelete:'set null'}),status:text('status').notNull().default('draft'),body:text('body').notNull().default('{}'),privateData:text('private_data').notNull().default('{}'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('content_kind_status').on(t.kind,t.status),index('content_organization').on(t.organizationId),index('content_owner').on(t.ownerId)]);
export const memberships=sqliteTable('memberships',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),organizationId:text('organization_id').notNull().references(()=>content.id,{onDelete:'cascade'}),role:text('role').notNull().default('member'),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.organizationId]}),index('memberships_org_status').on(t.organizationId,t.status)]);
export const interactions=sqliteTable('interactions',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),itemId:text('item_id').notNull().references(()=>content.id,{onDelete:'cascade'}),kind:text('kind').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.itemId,t.kind]}),index('interactions_item_kind').on(t.itemId,t.kind)]);
export const applications=sqliteTable('applications',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),itemId:text('item_id').notNull().references(()=>content.id,{onDelete:'cascade'}),note:text('note').notNull(),profile:text('profile').notNull(),status:text('status').notNull().default('submitted'),answers:text('answers').notNull().default('[]'),knockout:integer('knockout').notNull().default(0),rating:integer('rating'),matchScore:integer('match_score'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('applications_unique').on(t.userId,t.itemId),index('applications_item').on(t.itemId)]);

// ATS denetim izi: status dəyişikliyi, qeyd, qiymət.
export const applicationEvents=sqliteTable('application_events',{id:text('id').primaryKey(),applicationId:text('application_id').notNull().references(()=>applications.id,{onDelete:'cascade'}),actorId:text('actor_id').references(()=>users.id,{onDelete:'set null'}),type:text('type').notNull(),body:text('body').notNull().default('{}'),createdAt:integer('created_at').notNull()},t=>[index('application_events_app').on(t.applicationId,t.createdAt)]);

export const contentViews=sqliteTable('content_views',{itemId:text('item_id').primaryKey().references(()=>content.id,{onDelete:'cascade'}),count:integer('count').notNull().default(0)});
export const registrations=sqliteTable('registrations',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),itemId:text('item_id').notNull().references(()=>content.id,{onDelete:'cascade'}),status:text('status').notNull().default('registered'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('registrations_unique').on(t.userId,t.itemId),index('registrations_item_status').on(t.itemId,t.status)]);
export const progress=sqliteTable('progress',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),itemId:text('item_id').notNull().references(()=>content.id,{onDelete:'cascade'}),completed:text('completed').notNull().default('[]'),score:integer('score'),certificateId:text('certificate_id'),updatedAt:integer('updated_at').notNull()},t=>[primaryKey({columns:[t.userId,t.itemId]}),uniqueIndex('progress_certificate').on(t.certificateId)]);
export const contributions=sqliteTable('contributions',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),organizationId:text('organization_id').notNull().references(()=>content.id,{onDelete:'cascade'}),kind:text('kind').notNull(),body:text('body').notNull(),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull()},t=>[index('contributions_org_status').on(t.organizationId,t.status),index('contributions_user').on(t.userId)]);
export const votes=sqliteTable('votes',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),categoryId:text('category_id').notNull().references(()=>content.id,{onDelete:'cascade'}),candidateId:text('candidate_id').notNull().references(()=>content.id,{onDelete:'cascade'}),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.categoryId]}),index('votes_category_candidate').on(t.categoryId,t.candidateId)]);
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),title:text('title').notNull(),link:text('link').notNull(),read:integer('read').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('notifications_user_date').on(t.userId,t.createdAt)]);
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),name:text('name').notNull(),type:text('type').notNull(),category:text('category').notNull(),size:integer('size').notNull(),createdAt:integer('created_at').notNull()},t=>[index('uploads_user').on(t.userId)]);
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),kind:text('kind').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('documents_user_kind').on(t.userId,t.kind)]);
export const subscriptions=sqliteTable('subscriptions',{userId:text('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}),plan:text('plan').notNull().default('free'),status:text('status').notNull().default('active'),expiresAt:integer('expires_at'),stripeCustomer:text('stripe_customer'),stripeSubscription:text('stripe_subscription'),trialUsed:integer('trial_used').notNull().default(0)});
export const redemptions=sqliteTable('redemptions',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),itemId:text('item_id').notNull().references(()=>content.id,{onDelete:'cascade'}),code:text('code').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.itemId]})]);
export const usage=sqliteTable('usage',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),period:text('period').notNull(),kind:text('kind').notNull(),count:integer('count').notNull().default(0)},t=>[primaryKey({columns:[t.userId,t.period,t.kind]})]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),userId:text('user_id'),action:text('action').notNull(),itemId:text('item_id'),createdAt:integer('created_at').notNull()});
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const paymentEvents=sqliteTable('payment_events',{id:text('id').primaryKey(),createdAt:integer('created_at').notNull()});
